### ISSUE TITLE
Explorer.correlation_plot() uses deprecated Plotly method

### ISSUE THREAD

**Issue by srstevenson** [ASIDataScience/lens#16]
Calling `lens.explorer.Explorer.correlation_plot()` shows the following deprecation warning:
```
/opt/anaconda/envs/Python3/lib/python3.6/site-packages/plotly/tools.py:1422: UserWarning:

plotly.tools.FigureFactory.create_annotated_heatmap is deprecated. Use plotly.figure_factory.create_annotated_heatmap
```

**Comment by zblz** [comment]
Not sure why this is coming up, the `figure_factory` import looks like this to support both the pre-2.0 and 2.0 plotly API:
```
try:
    import plotly.figure_factory as pff
except ImportError:
    from plotly.tools import FigureFactory as pff
```

However, now that plotly.py 2.0 has been out for a while, it makes sense to only use the current API. I'll open a PR to require plotly >= 2.0 and use the new import path.
